CREATE TABLE PRODUCTOS_TERMINADOS (
    CODIGO INT,
    NOMBRE VARCHAR(25),
    CANTIDAD INT
    CONSTRAINT PK_PRODUCTOS_TERMINADOS PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUCCION (
    CODIGO_CLIENTE VARCHAR(25),
    CODIGO_PRODUCTO INT,
    CANTIDAD INT,
    FECHA DATE
    
)