CREATE TABLE PRODUCTOS_TERMINADOS (
    CODIGO INT,
    NOMBRE VARCHAR(25),
    CANTIDAD INT
    CONSTRAINT PK_PRODUCTOS_TERMINADOS PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUCCION_PEDIDOS (
    CODIGO_CLIENTE VARCHAR(25),
    CODIGO_PRODUCTO INT,
    CANTIDAD INT,
    FECHA DATE
);

CREATE OR REPLACE FUNCTION F_INSERT_PP (CC VARCHAR(25), CP INT, CANT INT, FECHA DATE)
RETURN INTEGER
IS 
BEGIN 
    INSERT INTO PRODUCCION_PEDIDOS VALUES (CC, CP, CANT, FECHA);
    EXCEPTION 
        WHEN VALUE_ERROR THEN
            RETURN 0;
        WHEN OTHERS THEN
            RETURN 0;
    RETURN 1;
END;
/

CREATE OR REPLACE PROCEDURE P1_PP (CC VARCHAR(25), CP INT, CANT INT, FECHA DATE)
IS
OK INTEGER;
    OK := F_INSERT_PP (CC, CP, CANT, FECHA);
    IF OK = 0 THEN
        ROLLBACK;
    ELSE
        COMMIT;
    END IF;
END;
/